// <auto-generated />
namespace GringotsDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_repository_pattern : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_repository_pattern));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171556224_initial_repository_pattern"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
