// <auto-generated />
using System;
using BakerySystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BakerySystem.Migrations
{
    [DbContext(typeof(BakeryDbContext))]
    [Migration("20260305075853_VendorInfosOptional")]
    partial class VendorInfosOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BakerySystem.Domain.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseUnit")
                        .HasColumnType("integer")
                        .HasColumnName("base_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("BakerySystem.Domain.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("BakerySystem.Domain.Vendor", b =>
                {
                    b.OwnsOne("BakerySystem.Domain.BankingInfo", "BankingInfo", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BankName")
                                .HasColumnType("text")
                                .HasColumnName("banking_info_bank_name");

                            b1.Property<string>("Iban")
                                .HasColumnType("text")
                                .HasColumnName("banking_info_iban");

                            b1.Property<string>("Swift")
                                .HasColumnType("text")
                                .HasColumnName("banking_info_swift");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId")
                                .HasConstraintName("fk_vendors_vendors_id");
                        });

                    b.OwnsOne("BakerySystem.Domain.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .HasColumnType("text")
                                .HasColumnName("contact_info_address");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("contact_info_city");

                            b1.Property<string>("Country")
                                .HasColumnType("text")
                                .HasColumnName("contact_info_country");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("contact_info_email");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text")
                                .HasColumnName("contact_info_phone_number");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId")
                                .HasConstraintName("fk_vendors_vendors_id");
                        });

                    b.OwnsOne("BakerySystem.Domain.LegalInfo", "LegalInfo", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("LegalAddress")
                                .HasColumnType("text")
                                .HasColumnName("legal_info_legal_address");

                            b1.Property<string>("Mol")
                                .HasColumnType("text")
                                .HasColumnName("legal_info_mol");

                            b1.Property<string>("Uic")
                                .HasColumnType("text")
                                .HasColumnName("legal_info_uic");

                            b1.Property<string>("VatNumber")
                                .HasColumnType("text")
                                .HasColumnName("legal_info_vat_number");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId")
                                .HasConstraintName("fk_vendors_vendors_id");
                        });

                    b.Navigation("BankingInfo");

                    b.Navigation("ContactInfo");

                    b.Navigation("LegalInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
